config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pals#input'

  get 'pals/input'
  get 'pals/output'
  get 'pals/all'
  get 'pals/create_article'
  get 'pals/delete_article'
  get 'pals/edit_article'
  get 'pals/showall'

  get '/:locale' => 'pals#input'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pal.rb
class Pal < ApplicationRecord
  validates :count, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/pals_controller.rb
class PalsController < ApplicationController
  before_action :authenticate_user!
  before_action :parse_params, only: :output
  before_action :set_locale

  def input
    @phrase = Pal.connection.execute('SELECT  "pals"."count" FROM "pals" ORDER BY RANDOM() LIMIT 1')

    if !@phrase.empty?
      @phrase = @phrase[0][0]
    end
  end

  def all
    @res = Pal.all
    render xml: @res.as_json.to_xml
  end

  def showall
    @res = Pal.all.to_a
  end

  def edit_article
    @res = Pal.find_by(count: params[:text])

    if @res.author != current_user.email
      abort('Критическая ошибка!')
    end

    if !@res.new_record? && !params[:article].empty? && !params[:photo_link].empty? && !params[:sdr].empty?
      @res.update(res: params[:article])
      @res.update(photo: params[:photo_link])
      @res.update(shortDesc: params[:sdr])
      @status = true
    else
      @status = false
    end

    respond_to do |format|
      format.html
    end
  end

  def delete_article
    @res = Pal.find_by(count: params[:text])

    if @res.author != current_user.email
      abort('Критическая ошибка!')
    end

    if @res.new_record?
      @status = false
    else
      @res.destroy
      @status = true
    end

    respond_to do |format|
      format.html
    end
  end

  def create_article
    @pal = Pal.find_or_initialize_by(count: params[:text])
    if @pal.new_record? && !params[:article].empty? && !params[:photo_link].empty? && !params[:sdr].empty?
      @pal.count = params[:text]
      @pal.res = params[:article]
      @pal.author = current_user.email
      @pal.photo = params[:photo_link]
      @pal.shortDesc = params[:sdr]
      @pal.save

      respond_to do |format|
        format.html
      end
    end
  end

  def output
    if params[:getrandarticle]
      @text = Pal.connection.execute('SELECT  "pals"."count" FROM "pals" ORDER BY RANDOM() LIMIT 1')

      if !@text.empty?
        @text = @text[0][0]
      end
    end

    @pal = Pal.find_or_initialize_by(count: @text)
    @pal.new_record? ? @status = 'no-content' : @status = 'ok'

    respond_to do |format|
      format.html
    end
  end

  protected

  def parse_params
    @text = params[:text]
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pals_helper.rb
module PalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Онлайн-энциклопедия</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="Content-Language" content="ru">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <!-- Main Quill library -->
    <script src="//cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js"></script>

    <!-- Theme included stylesheets -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/monokai-sublime.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" rel="stylesheet">

    <!-- Core build with no theme, formatting, non-essential modules -->
    <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
    <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script type="text/javascript" src="http://katalogtepla.com/catalog/view/javascript/jquery/remodal.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://katalogtepla.com/catalog/view/javascript/jquery/remodal.css">
    <link rel="stylesheet" type="text/css" href="http://katalogtepla.com/catalog/view/javascript/jquery/remodal-default-theme.css">
    <script src="https://cdn.webrtc-experiment.com/Translator.js"> </script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="form-inline my-2 my-lg-0">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item a-main"><%= link_to t('title'), pals_input_url %></a></li>
          <% if user_signed_in? %>
            <li class='nav-item'><%= link_to current_user.email, edit_user_registration_path, class: 'btn btn-outline-success col' %></li>
            <li class='nav-item'><%= link_to t('exit'), destroy_user_session_path, class: 'btn btn-warning col', method: :delete %></li>
          <% else %>
            <li class='nav-item'><%= link_to t('registration'), new_user_registration_path, class: 'btn btn-outline-light col' %></li>
            <li class='nav-item'><%= link_to t('enter'), new_user_session_path, class: 'btn btn-success col' %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="h-cat">
      <%= link_to t('all_articles'), pals_showall_url %>
      <a href="/pals/output?getrandarticle=true&locale=<%= params[:locale] == nil ? 'en' : params[:locale] %>"><%= t('chance') %></a>
      <div class="set_locale"><a href="#"><span class="locale active"><%= params[:locale] == 'ru' ?  t('russian') : t('english') %></span></a><a href="?locale=<%= params[:locale] == 'ru' ?  'en' : 'ru' %>"><br><span class="locale"><%= params[:locale] == 'ru' ?  t('english') : t('russian') %></span></a></div>
    </div>

    <div class="main-bg carousel-animate">
      <div class="element el-1" style="background: url('https://bigenc.ru/media/2018/07/19/1237695504/33716.jpg.1440x-.png')"><div class="f-bg"></div><div class="txt-content"><h3><%= t('s1') %></h3><p><%= t('c1') %></p></div></div>
      <div class="element el-2" style="background: url('https://bigenc.ru/media/2018/07/19/1237695505/33745.jpg.1440x-.png')"><div class="f-bg"></div><div class="txt-content"><h3><%= t('s2') %></h3><p><%= t('c2') %></p></div></div>
      <div class="element el-3" style="background: url('https://bigenc.ru/media/2018/07/19/1237695511/36207.jpg.1440x-.png')"><div class="f-bg"></div><div class="txt-content"><h3><%= t('s3') %></h3><p><%= t('c3') %></p></div></div>
      <div class="element el-4" style="background: url('https://bigenc.ru/media/2018/07/19/1237695510/33547.jpg.1440x-.png')"><div class="f-bg"></div><div class="txt-content"><h3><%= t('s4') %></h3><p><%= t('c4') %></p></div></div>
    </div>

    <style>
      .set_locale {
        display: inline-block;
        color: white;
        cursor: pointer;
        float: right;
        text-transform: lowercase;
        text-align: right;
        height: 37px;
        overflow: hidden;
        -webkit-transition: 0.5s ease all;
        transition: 0.5s ease all;
        position: relative;
      }

      .set_locale:hover {
        height: 100%;
      }

      .set_locale:hover span.locale {
        opacity: 1;
      }

      span.locale:hover {
        background: #007bff;
        border-color: transparent;
      }

      span.locale {
        display: inline-block;
        opacity: 0;
        -webkit-transition: 0.5s ease all;
        transition: 0.5s ease all;
        border: 1px solid white;
        padding: 5px 10px;
        border-radius: 3px;
        margin-bottom: 10px;
      }

      span.locale.active {
        opacity: 1;
      }
      .h-cat {
        position: relative;
        z-index: 1;
        padding: 10px 27px;
        width: 100%;
      }
      h2, h3, p {
        color: white;
      }
      .h-cat a {
        color: white;
        margin-right: 30px;
      }
      form#edit_user {
        color: white;
      }
      li.nav-item {
        margin: 0;
        padding: 7px 10px;
      }
      li.nav-item.a-main a {
        font-size: 24px;
        text-decoration: none;
        color: white;
        transition: 0.5s ease all;
      }

      li.nav-item.a-main a:hover {
        color: #46ccff;
      }
      .f-bg {
        position: absolute;
        background: linear-gradient(to bottom, rgba(0,0,0,.1)0%, rgba(0,0,0,.8)100%);
        opacity: 1;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
      }
      .carousel-animate {
        display: inline-block;
        width: 100%;
        height: 100%;
        position: absolute;
        margin-top: -44px;
      }

      .carousel-animate .element {
        position: relative;
        height: inherit;
        background-position: center !important;
        background-size: cover !important;
        display: none;
      }
      .main-bg h3, .main-bg p  {
        text-align: center;
        color: white;
      }
      .txt-content {
        position: absolute;
        bottom: 100px;
        width: 100%;
      }
      .el-<%= rand(1..4) %> {
        display: block !important;
      }
      nav.navbar.navbar-expand-lg.navbar-dark.bg-dark {
        min-height: 68px;
      }
      .form-inline.my-2.my-lg-0.fix {
        position: fixed;
        z-index: 20;
        width: 100%;
        background: #333a41;
        top: 0;
        left: 0;
        padding: 5px 15px;
      }
      label {
        color: white;
      }
    </style>
    <script>
        window.onscroll = function() {
            if(window.pageYOffset > 100) {
                $('.form-inline.my-2.my-lg-0').addClass('fix');
            } else {
                $('.form-inline.my-2.my-lg-0').removeClass('fix');
            }
        }
    </script>
    <div class="container col-11">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pals/create_article.html.erb
<h2><%= t('added_message') %></h2>

<h3><%= t('added_message_below') %></h3>

<a href="/pals/output?utf8=%E2%9C%93&text=<%= params[:text] %>"><%= t('ling_go_article') %></a>

<style>
  .container.col-11 {
    text-align: center;
    color: white;
    padding: 100px;
  }
</style>

app/views/pals/delete_article.html.erb
<% if @status %>
  <h2><%= t('delete_message') %></h2>
<% else %>
  <h2><%= t('undelete_message') %></h2>
<% end %>

<style>
  .container.col-11 {
    text-align: center;
    color: white;
    padding: 100px;
  }
</style>

app/views/pals/edit_article.html.erb
<% if @status %>
  <h2><%= t('edit_message') %></h2>
<% else %>
  <h2><%= t('unedit_message') %></h2>
<% end %>

<style>
  .container.col-11 {
    text-align: center;
    color: white;
    padding: 100px;
  }
</style>

app/views/pals/input.html.erb
<h3 class="text-search"><%= t('heading_title') %></h3>
<%= form_tag("/pals/output", method: :get, class: 'form-search') do %>
	<%= text_field_tag(:text, @phrase, class: 'form-control') %>
	<%= text_field_tag(:locale, params[:locale] == nil ? 'en' : params[:locale], class: 'form-control d-none') %>
	<%= submit_tag(t('search'), class: 'btn btn-primary go') %>
<% end %>

<style>
	.go {
		width: 100%;
		margin-top: 10px;
		background: transparent;
		border: 1px solid white;
		border-radius: 1px;
		font-size: 20px;
	}

		.text-search {
			text-align: center;
			color: #fff;
			line-height: 1.1em;
			font-weight: 100;
			margin-bottom: 40px;
			font-size: 40px;
			font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif;
		}
	.container.col-11 {
		position: relative;
		top: 50px;
	}
</style>

app/views/pals/output.html.erb
<div class="res remodal-bg">
	<% if @status == 'no-content' %>
		<h3><%= t('adding_article') %> <%= params[:text] %></h3>
		<br>
		<div class="plainlinks" style="border:1px solid #a2a9b1; padding:0.25em 1em; margin-bottom:1em; background:#F5FАFF; color:black;">
			<p><%= t('no_artciles_message') %></p>
			<hr>

			<%= raw t('block_advices_before_adding_artciles') %>

		</div>

		<div class="get_photo"><div class="preview_url_photo" style="
		background: url('http://zabavnik.club/wp-content/uploads/Kartinka_3_26040225.png');
		"></div><input onchange="setPhoto(this.value)" class="url_img" type="text" placeholder="<%= t('placeholder_img_link') %>"></div>
		<div class="params"><p><%= t('additionaly_params_message') %>:</p><input type="text" class="short_desc rus" placeholder="<%= t('sd_msg') %>"></div>
		<br>
		<div id="editor-container" style="height: 375px;">
		</div>
		<br>
		<div class="btn btn-primary" onclick="sendArticle()"><%= t('button_save_text') %></div>
	<% elsif @status == 'ok' %>
		<img style="margin: auto;display: inherit;max-width: 900px" src="<%= @pal.photo %>">
		<br>
		<hr>
		<div class="html-container"><%= @pal.res.html_safe %></div>
		<% if params[:locale] == 'en' || params[:locale] == nil %>
			<!-- <a href="#" class="translate">translate it!</a> -->
		<% end %>
		<p><%= t('published') %>: <%= @pal.created_at.strftime("%H:%M:%S %Y.%m.%d") %></p>
		<p><%= t('author') %>: <%= @pal.author %></p>
		<% if current_user.email == @pal.author %>
		<p class="editor-block"><%= t('editor_block_message') %>:<br><a data-remodal-target="modal" href="#"><%= t('action_edit_message') %></a><a onclick="deleteArticle(); return false;" href="#"><%= t('action_delete_message') %></a></p>
		<script>
			function editArticle() {
          let content = quill.getContents(); content = quillGetHTML(content);
          let url = $('.url_img').val();
          let text = getFromUrl('text');
          let locale = getFromUrl('locale');
          let short_desc_rus = $('.short_desc.rus').val();

          if(!locale) {
              locale = 'en';
          }

          if(content == '' || url == '' || text == '' || short_desc_rus == '') {
              alert('<%= t('error_add_content') %>');
          } else {
              window.open("/pals/edit_article?utf8=%E2%9C%93&text="+text+"&article="+encodeURIComponent(content)+"&photo_link="+url+"&sdr="+short_desc_rus+"&locale="+locale,"_self")
          }
			}

			function deleteArticle() {
          let text = getFromUrl('text');
          let locale = getFromUrl('locale');

          if(!locale) {
              locale = 'en';
          }

          window.open("/pals/delete_article?utf8=%E2%9C%93&text="+text+"&locale="+locale,"_self")
			}
		</script>
			<div class="remodal" data-remodal-id="modal">
				<button data-remodal-action="close" class="remodal-close"></button>
				<h2><%= t('editing_article_msg') %> <%= @pal.count %></h2>
				<div><div class="preview_url_photo" style="
				background: url('<%= @pal.photo %>');
				"></div><p><%= t('photo_msg') %>:</p><input value="<%= @pal.photo %>" onchange="setPhoto(this.value)" class="url_img editor" type="text" placeholder="<%= t('placeholder_img_link') %>"><br><br><p><%= t('additionaly_params_message') %>:</p><input type="text" value="<%= @pal.shortDesc %>" class="short_desc rus" placeholder="<%= t('sd_msg') %>"></div>
				<br>
				<div id="editor-container" style="height: 375px;">
				</div>
				<br>
				<button data-remodal-action="cancel" style="border-radius: 3px; padding: 13px 10px" class="remodal-cancel"><%= t('btn_cancel') %></button>
				<button data-remodal-action="confirm" style="border-radius: 3px; padding: 13px 10px" class="remodal-confirm" onclick="editArticle()"><%= t('button_save_text') %></button>
			</div>
		<% end %>
		<script>
        window.onload = function() {
            $('.element').css( { 'background': 'white url(https://techport-st.cdn.ngenix.net/assets/images/51534b4186014ecedd4e6fe573580c24.png)' } );
            $('.txt-content h3').html('<%= @pal.count %>');
            $('.txt-content p').html('<%= @pal.shortDesc %>');
        };
		</script>
		<style>
		.carousel-animate .element {
				background-size: unset !important;
			}
			</style>
	<% end %>
</div>

	<style>
		a.translate {
			font-size: 12px;
			position: relative;
			bottom: 1rem;
		}
		input.url_img.editor {
			width: calc(100% - 100px);
			position: relative;
			top: 0;
			margin: 0;
		}
		p.editor-block a {
			margin-right: 20px;
		}

		p.editor-block {
			font-size: 12px;
		}
		.params {
			width: 49%;
			display: inline-block;
			padding: 10px;
			position: absolute;
		}
		input.short_desc {
			width: calc(100% - 100px);
			min-width: 100px;
			margin-bottom: 20px;
		}
		.get_photo {
			padding: 10px;
			position: relative;
			width: 50%;
			display: inline-block;
		}

		input.url_img {
			width: calc(100% - 265px);
			position: absolute;
			top: 100px;
			margin-left: 25px;
		}

		.preview_url_photo {
			width: 200px;
			height: 200px;
			background-size: cover !important;
			display: inline-block;
			border-radius: 100%;
			background-position: center !important;
		}
		.container {
			padding-bottom: 20px;
		}
		.txt-content {
			bottom: unset !important;
			padding: 35px;
		}

		.main-bg.carousel-animate {
			height: 150px;
		}
			.res {
				margin-top: 200px;
			}
		button.ql-image {
			display: none !important;
		}
		h2, h3, p {
			color: black;
		}
		</style>
<script>
    function setPhoto(url) {
        let objRE = /(http|https):\/\/(\w+:{0,1}\w*)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%!\-\/]))?/;

        if(objRE.test(url)) {
            $('.preview_url_photo').css('background', 'url(' + url + ')');
        }
    }
    var quill = new Quill('#editor-container', {
        modules: {
            toolbar: [
                [{ header: [1, 2, false] }],
                ['bold', 'italic', 'underline'],
                ['image', 'code-block']
            ]
        },
        placeholder: '<%= t('placeholder_editor') %> <%= params[:text] %>',
        theme: 'snow'
    });

    <% if current_user.email == @pal.author %>

    document.querySelector(".ql-editor").innerHTML = '<%= @pal.res.html_safe %>';

    <% end %>

    function quillGetHTML(inputDelta) {
        var tempCont = document.createElement("div");
        (new Quill(tempCont)).setContents(inputDelta);
        return tempCont.getElementsByClassName("ql-editor")[0].innerHTML;
    }

    function getFromUrl(key) {
        var s = window.location.search;
        s = s.match(new RegExp(key + '=([^&=]+)'));
        return s ? s[1] : false;
    }

    function sendArticle() {
        let content = quill.getContents(); content = quillGetHTML(content);
        let url = $('.url_img').val();
        let text = getFromUrl('text');
        let locale = getFromUrl('locale');
        let short_desc_rus = $('.short_desc.rus').val();

        if(!locale) {
            locale = 'en';
				}

        if(content == '' || url == '' || text == '' || short_desc_rus == '') {
            alert('<%= t('error_add_content') %>');
				} else {
            window.open("/pals/create_article?utf8=%E2%9C%93&text="+text+"&article="+encodeURIComponent(content)+"&photo_link="+url+"&sdr="+short_desc_rus+"&locale="+locale,"_self")
        }
		}
</script>

app/views/pals/showall.html.erb
<div class="res">
  <h3><%= t('all_articles') %></h3>
  <ul>
  <% @res.count.times do |i| %>
      <li><a href="/pals/output?utf8=✓&text=<%= @res[i]['count'] %>"><%= @res[i]['count'] %></a><p><%= @res[i]['shortDesc'] %></p></li>
  <% end %>
  </ul>
</div>

<style>
.container {
padding-bottom: 20px;
}
.txt-content {
bottom: unset !important;
padding: 35px;
}

.main-bg.carousel-animate {
height: 150px;
}
.res {
margin-top: 200px;
}
h2, h3, p {
  color: black;
}
</style>